---
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes
  vars:
    kube_version: "v1.28.0"
    group: "appowner"
    container_runtime: containerd
    network: calico
    service_cidr: "10.96.0.0/12"
    pod_network_cidr: "10.244.0.0/16"
    control_plane_ip: "20.108.66.230"
    kubeadm_opts: ""
    init_opts: ""

  tasks:
    - name: Ensure apt keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      become: yes

    - name: Load kernel modules
      shell: |
        modprobe overlay
        modprobe br_netfilter
      become: yes

    - name: Create containerd config file
      file:
        path: "/etc/modules-load.d/containerd.conf"
        state: touch
      become: yes

    - name: Add containerd kernel modules to config
      blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        block: |
          overlay
          br_netfilter
      become: yes

    - name: Set system configurations for Kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: touch
      become: yes

    - name: Add sysctl settings
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
      become: yes

    - name: Apply sysctl settings
      command: sysctl --system
      become: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Get OS release name
      command: "lsb_release -cs"
      changed_when: false
      register: lsb_rel
      become: yes

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_rel.stdout }} stable
        state: present
        update_cache: yes
      when: ansible_distribution_release == 'Ubuntu'

    - name: Install containerd
      apt:
        update_cache: yes
        name: containerd.io
      become: yes

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        systemctl restart containerd
      become: yes

    - name: Ensure Kubernetes GPG key exists
      stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: kubernetes_gpg_key
      become: yes

    - name: Add Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        dest: /tmp/kubernetes-apt-key.gpg
      when: not kubernetes_gpg_key.stat.exists
      become: yes

    - name: Import Kubernetes GPG key
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-key.gpg
      when: not kubernetes_gpg_key.stat.exists
      become: yes

    - name: Add Kubernetes APT repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
      become: yes

    - name: Install Kubernetes components
      apt:
        update_cache: yes
        pkg:
          - kubelet
          - kubeadm
          - kubectl
        state: present
      become: yes

    - name: Exclude kube components from apt upgrades
      shell: |
        apt-mark hold kubelet kubeadm kubectl containerd.io
      become: yes

    - name: Enable containerd service
      systemd:
        state: started
        name: containerd.service
        enabled: yes
        daemon_reload: yes
      become: yes

    - name: Enable kubelet service
      systemd:
        state: started
        name: kubelet.service
        enabled: yes
        daemon_reload: yes
      become: yes

- name: Initialize Kubernetes Control Plane
  hosts: k8s_master
  become: yes
  vars:
    kube_version: "v1.28.0"
    group: "appowner"
    container_runtime: containerd
    network: calico
    service_cidr: "10.96.0.0/12"
    pod_network_cidr: "10.244.0.0/16"
    control_plane_ip: "20.108.66.230"
    kubeadm_opts: ""
    init_opts: ""

  tasks:
    - name: Create appowner group if it doesn't exist
      group:
        name: "{{ group }}"
        state: present
      become: yes

    - name: Reset Kubernetes components
      shell: "kubeadm reset --force --cri-socket=/var/run/{{ container_runtime }}/{{ container_runtime }}.sock"
      become: yes
      register: reset_cluster
      ignore_errors: yes

    - name: Initialize Kubernetes cluster
      when: reset_cluster is succeeded
      shell: |
        kubeadm init --pod-network-cidr={{ pod_network_cidr }}
      become: yes
      register: init_cluster

    - name: Create user .kube directory
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "/home/{{ ansible_user }}/.kube"
        - "/root/.kube"
      become: yes

    - name: Copy admin.conf to user home directory
      copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "{{ item }}/.kube/config"
        owner: "{{ ansible_user | default('root') }}"
        group: "{{ group | default('root') }}"
        mode: 0644
        remote_src: yes
      with_items:
        - "/home/{{ ansible_user }}"
        - "/root"
      become: yes

    - name: Install pod network
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
      become: yes

    - name: Add k alias for user
      lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: "alias k='kubectl'"
        owner: "{{ ansible_user }}"
        regexp: '^alias k=''kubectl''$'
        state: present
        insertafter: EOF
        create: True
      become: yes

- name: Join Worker Node
  hosts: k8s_worker
  become: yes
  vars:
    kube_version: "v1.28.0"
    group: "appowner"
    container_runtime: containerd
    network: calico
    service_cidr: "10.96.0.0/12"
    pod_network_cidr: "10.244.0.0/16"
    control_plane_ip: "20.108.66.230"
    kubeadm_opts: ""
    init_opts: ""

  tasks:
    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: kubeadm_join_cmd
      become: yes
      ignore_errors: yes

    - set_fact:
        kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

    - name: Join worker node to cluster
      shell: "{{ kubeadm_join_cmd }}"
      register: join_output
      ignore_errors: yes
      become: yes

    - name: Check join command output
      debug:
        msg: "{{ join_output.stdout }}"
      become: yes

- name: Verify Cluster Status
  hosts: k8s_master
  become: yes
  vars:
    kube_version: "v1.28.0"
    group: "appowner"
    container_runtime: containerd
    network: calico
    service_cidr: "10.96.0.0/12"
    pod_network_cidr: "10.244.0.0/16"
    control_plane_ip: "20.108.66.230"
    kubeadm_opts: ""
    init_opts: ""

  tasks:
    - name: Check nodes status
      command: kubectl get nodes
      register: nodes_status
      become: yes

    - name: Display nodes status
      debug:
        msg: "{{ nodes_status.stdout }}"
      become: yes

    - name: Check pods status in kube-system namespace
      command: kubectl get pods -n kube-system
      register: pods_status
      become: yes

    - name: Display pods status
      debug:
        msg: "{{ pods_status.stdout }}"
      become: yes

- name: Update
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist
      become: yes

    - name: Reboot if requested by the system
      shell: sleep 10 && /sbin/shutdown -r now 'Rebooting as requested by the system'
      args:
        removes: /var/run/reboot-required
      async: 1
      poll: 0
      ignore_errors: yes
      become: yes
