- hosts: k8s_master
  become: yes
  tasks:
    - name: Clean up any existing Kubernetes setup
      shell: kubeadm reset -f && rm -rf /etc/kubernetes/manifests /var/lib/etcd /etc/kubernetes/kubelet.conf /etc/kubernetes/admin.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf
      ignore_errors: yes

    - name: create an empty file for Kubeadm configuring
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: no

    - name: configuring the container runtime including its cgroup driver
      blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
             kind: ClusterConfiguration
             apiVersion: kubeadm.k8s.io/v1beta3
             networking:
               podSubnet: "10.244.0.0/16"
             ---
             kind: KubeletConfiguration
             apiVersion: kubelet.config.k8s.io/v1beta1
             runtimeRequestTimeout: "15m"
             cgroupDriver: "systemd"
             systemReserved:
               cpu: 100m
               memory: 350M
             kubeReserved:
               cpu: 100m
               memory: 50M
             enforceNodeAllocatable:
             - pods

    - name: initialize the cluster (this could take some time)
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml >> cluster_initialized.log 2>&1
      args:
        chdir: /root
        creates: cluster_initialized.log

    - name: Display initialization log for debugging
      shell: cat /root/cluster_initialized.log
      register: init_log
      ignore_errors: yes

    - debug:
        msg: "{{ init_log.stdout }}"

    - name: create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
      ignore_errors: yes

    - name: install Pod network
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
      args:
        chdir: /root
        creates: pod_network_setup.log
      ignore_errors: yes
