version: '3.3'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306" 

  spring-boot-app:
    build: .
    container_name: spring-boot-container
    ports:
      - "8089:8089"
